CREATE TABLE gasto (
    id          BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(200)             NOT NULL,
    monto       INTEGER                  NOT NULL,
    categoria   VARCHAR(50)              NOT NULL,
    fecha       DATE                     NOT NULL,
    estado      VARCHAR(20)              NOT NULL DEFAULT 'PENDIENTE',
    comentario  VARCHAR(500),
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    usuario_id  VARCHAR(100)             NOT NULL,

    CONSTRAINT monto_no_negativo CHECK (monto >= 0),
    CONSTRAINT estado_valido CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO'))
);